### PR TITLE
Update to latest version of envify

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by adtaylor** [comment]
:+1:

**Comment by KyleAMathews** [comment]
@mjohnston merging this and pushing a new release would be very appreciated. If you're not actively using this module anymore, I'd be happy to take over maintaining it.

**Comment by mjohnston** [comment]
@KyleAMathews sorry, haven't been paying attention to this repo in awhile. Have you tried the transform-loader + envify? See: https://github.com/mjohnston/envify-loader/issues/1

I published this to npm before I was aware of this. I should probably add a disclaimer to the project and/or unpublish it from npm.

**Comment by KyleAMathews** [comment]
Ah gotcha :)

Makes perfect sense. Switching to transform-loader was easy.

Yeah, disclaimer here + perhaps deprecated on NPM instead of unpublishing. I think you can add a note when deprecating a module which you could use to point people to issue #1.

**Comment by mjohnston** [comment]
Added a notice to the README and deprecated the npm package. Thanks @KyleAMathews for the npm tip.

**Pull request closed without merging**
